name: elevater
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - cudatoolkit=11.0.221
  - freetype=2.10.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lerc=3.0
  - libdeflate=1.8
  - libpng=1.6.37
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.7.13
  - pytorch=1.7.0
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - torchvision=0.8.0
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.5
    - cycler==0.11.0
    - dataclasses==0.6
    - filelock==3.8.0
    - fonttools==4.37.3
    - ftfy==6.1.1
    - future==0.18.2
    - huggingface-hub==0.9.1
    - idna==3.4
    - importlib-metadata==4.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - nltk==3.7
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pillow==9.0.1
    - protobuf==3.20.2
    - pycocoevalcap==1.2
    - pycocotools==2.0.5
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==5.4.1
    - regex==2022.9.13
    - requests==2.28.1
    - sacremoses==0.0.53
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sharedmem==0.3.8
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - tokenizers==0.10.3
    - tqdm==4.62.3
    - transformers==4.11.3
    - urllib3==1.26.12
    - vision-datasets==0.2.18
    - vision-evaluation==0.2.9
    - wcwidth==0.2.5
    - yacs==0.1.8
    - zipp==3.8.1