description: elevater-zeroshot

target:
  service: amlk8s
  name: itphyperdgx2cl1
  vc: hai7a

environment:
  registry: mcr.microsoft.com
  image: azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04:latest
  conda_yaml_file: $CONFIG_DIR/environment.yml # requires amlt>=8.2.1.post1
  setup:
    - pip install git+https://github.com/openai/CLIP.git
    - pip install git+https://github.com/haotian-liu/CLIP_vlp.git
    - pip install -e .

# environment:
#   registry: mcr.microsoft.com
#   image: azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04:latest
#   conda_yaml_file: $CONFIG_DIR/environment.yml # requires amlt>=8.2.1.post1
#   image_setup:
#     - pip install yacs==0.1.8
#     - pip install scikit-learn
#     - pip install timm~=0.4.12
#     - pip install numpy~=1.21.0
#     - pip install sharedmem
#     - pip install git+https://github.com/openai/CLIP.git
#     - pip install git+https://github.com/haotian-liu/CLIP_vlp.git
#     - pip install torch~=1.7.0
#     - pip install PyYAML~=5.4.1
#     - pip install Pillow~=9.0.1
#     - pip install torchvision~=0.8.0
#     - pip install vision-evaluation>=0.2.2
#     - pip install vision-datasets>=0.2.0
#     - pip install tqdm~=4.62.3
#     - pip install transformers~=4.11.3
#     - pip install protobuf~=3.20.1
#     - pip install ftfy~=6.1.1
#     - pip install nltk~=3.7
#   setup:
#     - pip install .

code:
  local_dir: $CONFIG_DIR/..

storage:
  input_path:
    # You should use your own blob here
    storage_account_name: huinan
    container_name: amulet
  output_path:
    # You should use your own blob here
    storage_account_name: huinan
    container_name: amulet

jobs:
  - name: zeroshot-vitb16_CLIP
    sku: 32G16-V100
    command:
      - python vision_benchmark/commands/zeroshot.py
        --ds ./vision_benchmark/resources/datasets/mnist.yaml
        --model ./vision_benchmark/resources/model/vitb16_CLIP.yaml
        MODEL.CLIP_FP32 True
        DATASET.ROOT /mnt/input_path/elevater/datasets
        OUTPUT_DIR /mnt/output_path/elevater/vitb16_CLIP/log 
        KNOWLEDGE.WORDNET.USE_HIERARCHY False
        KNOWLEDGE.WORDNET.USE_DEFINITION False
        KNOWLEDGE.WIKITIONARY.USE_DEFINITION False
        KNOWLEDGE.GPT3.USE_GPT3 False
        KNOWLEDGE.AGGREGATION.NUM_GPT3_ITEMS 0
        TEST.MODEL_FILE "."
        $EXTRA_ARGS
    submit_args:
      max_attempts: 1
